### ISSUE TITLE
Receive 404 with local server setup in Chrome..

### ISSUE THREAD

**Issue by joshbaptiste** [progrium/termshare#2]
charlie:~ $ PORT=8888 termshare -d 
2013/12/15 16:14:15 Termshare server started...

now when connecting with client
charlie:~ $ termshare -s 127.0.0.1:8888
 _                          _  
| |_ ___ _ __ _ __ ___  ___| |__   __ _ _ __ ___ 
| **/ _ \ '**| '_ `_ \/ __| '_ \ / _` | '**/ _ \
| ||  __/ |  | | | | | \** \ | | | (_| | | |  __/
 _____|_|  |_| |_| |_|**_/_| |_|\**,_|_|  ___|

Session URL: http://termsha.re/e81c7303-3c93-48ea-672a-ddbf171c37d2

2013/12/15 16:14:15 Termshare server started...
2013/12/15 16:14:51 e81c7303-3c93-48ea-672a-ddbf171c37d2: session created
2013/12/15 16:14:51 e81c7303-3c93-48ea-672a-ddbf171c37d2: pilot connected

charlie:~ $ wget 'http://127.0.0.1:8888/e81c7303-3c93-48ea-672a-ddbf171c37d2'
--2013-12-15 16:22:04--  http://127.0.0.1:8888/e81c7303-3c93-48ea-672a-ddbf171c37d2
Connecting to 127.0.0.1:8888... connected.
HTTP request sent, awaiting response... 404 Not Found
2013-12-15 16:22:04 ERROR 404: Not Found.

**Comment by progrium** [comment]
There's a new version of the client if you re-download.

**Comment by joshbaptiste** [comment]
Hi,

I removed and re-installed via
charlie:~ curl -sL https://termsha.re/download/$(uname -s) | tar -C ~/bin
-zxf -

charlie:~ $ PORT=8888 termshare -d
2013/12/15 17:18:11 Termshare server started...
2013/12/15 17:20:38 c00e70c3-90d6-4632-47f3-4362b2552332: session created
2013/12/15 17:20:38 c00e70c3-90d6-4632-47f3-4362b2552332: pilot connected
2013/12/15 17:21:04 c00e70c3-90d6-4632-47f3-4362b2552332: viewer connected
(browser)

charlie:~ $ wget 'http://127.0.0.1:8888/c00e70c3-90d6-4632-47f3-4362b2552332
'
--2013-12-15 17:21:04--
http://127.0.0.1:8888/c00e70c3-90d6-4632-47f3-4362b2552332
Connecting to 127.0.0.1:8888... connected.
HTTP request sent, awaiting response... 404 Not Found
2013-12-15 17:21:04 ERROR 404: Not Found.

charlie:~ $ sha1sum ~/bin/termshare
f38085455ae85013d2a5c8aa3526e0043982cb36  /home/charlie/bin/termshare

**Comment by progrium** [comment]
There's actually a bug where it should return 200 no matter what. Are you sure something else isn't listening on 8888?

**Comment by joshbaptiste** [comment]
charlie:~ $ lsof -i:8888
COMMAND    PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
termshare 7848 charlie    3u  IPv6 4776554      0t0  TCP *:8888 (LISTEN)
termshare 7848 charlie    5u  IPv6 4780438      0t0  TCP
localhost:8888->localhost:38427 (ESTABLISHED)
termshare 7848 charlie    6u  IPv6 4780440      0t0  TCP
localhost:8888->localhost:38428 (ESTABLISHED)
termshare 7955 charlie    4u  IPv4 4774802      0t0  TCP
localhost:38427->localhost:8888 (ESTABLISHED)
termshare 7955 charlie    6u  IPv4 4774803      0t0  TCP
localhost:38428->localhost:8888 (ESTABLISHED)

Just the termshare server listening on 8888

I tried a different Linux box on a vps I have and same issue
I'll email you the link to my VPS termshare

**Comment by progrium** [comment]
Okay, I was wrong. There is a case where it will return 404 and that's if
it can't find the session. I can't really explain it and I'm just unable to
reproduce this. Let me try on Linux.

On Sun, Dec 15, 2013 at 3:08 PM, Reynold Chery notifications@github.comwrote:

> charlie:~ $ lsof -i:8888
> COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
> termshare 7848 charlie 3u IPv6 4776554 0t0 TCP *:8888 (LISTEN)
> termshare 7848 charlie 5u IPv6 4780438 0t0 TCP
> localhost:8888->localhost:38427 (ESTABLISHED)
> termshare 7848 charlie 6u IPv6 4780440 0t0 TCP
> localhost:8888->localhost:38428 (ESTABLISHED)
> termshare 7955 charlie 4u IPv4 4774802 0t0 TCP
> localhost:38427->localhost:8888 (ESTABLISHED)
> termshare 7955 charlie 6u IPv4 4774803 0t0 TCP
> localhost:38428->localhost:8888 (ESTABLISHED)
> 
> Just the termshare server listening on 8888
> 
> I tried a different Linux box on a vps I have and same issue
> I'll email you the link to my VPS termshare
> 
> On Sun, Dec 15, 2013 at 5:39 PM, Jeff Lindsay notifications@github.comwrote:
> 
> > There's actually a bug where it should return 200 no matter what. Are
> > you
> > sure something else isn't listening on 8888?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/progrium/termshare/issues/2#issuecomment-30623910>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/progrium/termshare/issues/2#issuecomment-30624567
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
Alright, I was able to reproduce. It's because it's trying to serve an HTML file that's not there. I've not tested running the daemon from the binary distribution since it's assumed it's run from the project repo which includes the HTML file. So in order to make the daemon work, I need to package the HTML file in with the binary maybe using go-bindata or something. For now just grab the term.html file from the repo and have in the directory you run the daemon.

**Comment by progrium** [comment]
Just put out a new release that resolves this. Also note the instructions in the readme:
https://github.com/progrium/termshare#running-the-termshare-server-locally

Let me know if this resolves the issue.

**Comment by joshbaptiste** [comment]
Works great locally now..
Thanks for quick fix!
