### ISSUE TITLE
termshare installation doesn't work on 32 bit Linux

### ISSUE THREAD

**Issue by eik3** [progrium/termshare#6]
I tried termshare with the installation instructions on my VPS that is a 32 bit Linux and got a "cannot execute binary file".
Downloading the source and building (after fiddling with `GOPATH` and `go get`) worked, though.

**Comment by progrium** [comment]
That's right, it doesn't directly support 32 bit but it can still be built
for 32 bit. I'd like to wait until there is more demand for 32 bit before
we start managing another build.

On Thu, Oct 16, 2014 at 4:50 AM, Eike Herzbach notifications@github.com
wrote:

> I tried termshare with the installation instructions on my VPS that is a
> 32 bit Linux and got a "cannot execute binary file".
> Downloading the source and building (after fiddling with GOPATH and go get)
> worked, though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/progrium/termshare/issues/6.

## 

Jeff Lindsay
http://progrium.com

**Comment by eik3** [comment]
Understandable. 
BTW thanks for termshare, great tool!
